services:
  mongodb:
    image: mongo:latest  
    container_name: markendation_mongo
    ports:          
      - "${TAILSCALE_IP}:${MONGODB_PORT}:27017"       # Radmin network access
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}  
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}  
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
      image: redis:7-alpine
      container_name: markendation_redis
      ports:
        - "${TAILSCALE_IP}:6380:6379"  
      volumes:
        - redis_data:/data
      command: redis-server --appendonly yes
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: markendation_rabbitmq
    ports:
      - "5672:5672"          
      - "15672:15672" 
      - "${RADMIN_IP}:5672:5672"               
      - "${RADMIN_IP}:15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped  

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data: